### PR TITLE
Update to thud 28.3.0

### PR DESCRIPTION
**Pull request by acostach**
- Update L4T to 28.3.0 to address issue https://github.com/balena-os/balena-jetson-skx2/issues/166
- Skx2 machine kernel stays at the same revision as it uses a different recipe.

### CODE REVIEW

**Comment by floion** [comment]
What tag is https://github.com/balena-os/balena-jetson-skx2/pull/167/commits/7d45cb8eadc5e3841dd3e11f6a83d7eae2d1e962 updating to?

**Comment by acostach** [comment]
@floion it's thud branch with tag thud-20.0.3 in poky. 

I have to look today into why that board fails, cause building locally tx2 and skx2 worked.

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by acostach** [comment]
@balena-ci retest

**Comment by floion** [comment]
@resin-jenkins test this please

**Pull request merged**
