### PR TITLE
jetson-odmdata1-tx2: Add TX2 Machine with ODMDATA 1 Config

### PR DESCRIPTION
**Pull request by mhodgson**
Add a new TX2-based machine with ODMDATA set for configuration #1 (0x90000).
Also include the Gasket kernel module to support PCIe-based Coral Edge TPUs.

Changelog-entry: Add a TX2 Machine with ODMDATA Config #1
Signed-off-by: Matt Hodgson <matthodgson@mac.com>

### CODE REVIEW

**Comment by floion** [comment]
Hi. Thank you for your contribution.
We have a set of contribution guidelines we follow for pull requests in our layer. These guidelines can be found here: https://github.com/balena-os/balena-jetson-skx2#contributing

Here is an this example from another contributor in this repo: https://github.com/balena-os/balena-jetson-skx2/pull/139 (with these follow-up commits: https://github.com/balena-os/balena-jetson-skx2/commit/cbad1ffb38b47f95a05ecddc72ba4601a6841f4d and https://github.com/balena-os/balena-jetson-skx2/commit/fa647a67c7fbbf0f781b50c82671c4c2dea6f1ad)

**Comment by mhodgson** [comment]
@floion I followed the contribution guidelines as best I can tell. Is there something that isn't correct?

**Comment by floion** [comment]
We tend to split by doing 1 commit per recipe / component

**Comment by mhodgson** [comment]
@floion ok, is that one commit per file? In this case should all the gasket files be in one commit? I'm not seeing any reference to this constraint in the contribution guidelines.

**Comment by acostach** [comment]
Hi @mhodgson , the links that Florin pasted as examples above show the commit you created should be split into multiple ones, per component. For instance the machine.conf should be one comit with the title "jetson-odmdata1-tx2: Add yocto machine". Then the coffe file, again a separate commit "jetson-odmdata1-tx2: Add coffe file" and a comment.. One changelog entry is sufficient per PR. The kernel driver should be added as a patch, here's an example: https://github.com/balena-os/balena-jetson-skx2/commit/298c68fac353f073977c17adc4a7ee4bf2b1e233 . The patch will be added in the existing  folder which holds the patches, one near the kernel yocto recipes, and the configs and patch will be mentioned in the recipe. The patch and the recipe should be added as a single commit, since there's always one commit per component. Please let me know if you encounter issues.

**Comment by mhodgson** [comment]
@acostach thanks for the clarification. Regarding the patch, I'm not sure I follow. I've been looking for examples for a while now, and every patch appears to just modify existing files. Do you have an example of a patch that adds an entire folder's worth of files? Never having used yocto, I'm really not clear how this is supposed to work.

**Comment by mhodgson** [comment]
I tried my best to follow the instructions here, which seem to apply in this case: https://www.yoctoproject.org/docs/2.6/kernel-dev/kernel-dev.html#incorporating-out-of-tree-modules

**Comment by acostach** [comment]
@mhodgson sure, here's an example of how a patch adding the gasket driver looked like:https://lwn.net/Articles/758745/  You can find the git dir for the tx2 kernel in your tx2 build directory. First add the existing git changes there to a commit that you'll ignore, then bring in there the sources for gasket and apex that work for you, create a commit with them and use git format patch HEAD -1 to obtain the final patch. The drivers should be added to the staging drivers in the git repo, like they are in the coral kernel repo. And you can ignore the oot project Makefile, since there's already a Makefile for them in the coral repository which builds them as modules or built-in, depending on the chosen configs. The kernel one should be added to the patch.

**Pull request closed without merging**
