### PR TITLE
 Add CTI Astro Carrier Board for NVidia Jetson TX2

### PR DESCRIPTION
**Pull request by c-wilson**
This adds the DTB and build references to enable builds for CTI Astro revision G boards. The build completes and flashes to a test TX2 running on this carrier board. USB and secondary ethernet ports are working as expected.

closes resin-os/resin-jetson-tx2#90

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-ci retest

**Comment by floion** [comment]
Thanks for the re-commit of the PR.
It looks good now, though there are a few changes needed still (sorry about that).
Can you redo the commits so that the commit header should be something like `component: <Short description of the commit (maximum 72 characters per line)>` then an new empty line and  then followed by a new paragraph in which you describe in detail the change? (again, maximum 72 characters per line).

**Comment by floion** [comment]
@c-wilson please see here https://github.com/balena-os/resin-jetson-tx2#pull-requests for details on commit guidelines

**Comment by floion** [comment]
Also, can you rebase the branch on master?

**Comment by floion** [comment]
re-ping @c-wilson ^

**Comment by keenanjohnson** [comment]
Hey all! This would be really helpful to me if it was mainline. What needs to be done to push this over the finish line? Just rebase-ing and revising the commit message?

**Comment by acostach** [comment]
> Hey all! This would be really helpful to me if it was mainline. What needs to be done to push this over the finish line? Just rebase-ing and revising the commit message?

Hey @keenanjohnson ,  please see my answer at https://github.com/balena-os/balena-jetson-skx2/pull/200#issuecomment-634488379

**Comment by keenanjohnson** [comment]
Thanks!

**Comment by floion** [comment]
Hi @c-wilson since @keenanjohnson has opened https://github.com/balena-os/balena-jetson/pull/71 , can you maybe close this PR? Thank you

**Comment by c-wilson** [comment]
hey guys, sorry I didn't follow through on this completely it seems like there's a better solution now anyway! Thanks!

**Comment by keenanjohnson** [comment]
No worries @c-wilson ! Feel free to follow along in the new PR and test it out if you want! I'd appreciate some more eyes on my work :)

https://github.com/balena-os/balena-jetson/pull/71

**Pull request closed without merging**
