### PR TITLE
component: Add CTI Astro Carrier Board for NVidia Jetson TX2

### LINKED ISSUE #90: CTI Astro board support
Would you be open to a PR extending support to CTI's Astro board for TX2? I see the approach used by @floion to add Spacely support, and it seems pretty straightforward to follow now that the path is defined. I'd be happy to contribute testing time.

With Resin OS patched, I assume that containers can be run without modification, is that correct?

### PR DESCRIPTION
**Pull request by keenanjohnson**
This adds the DTB and build references to enable builds for CTI Astro revision G boards. The build completes and flashes to a test TX2 running on this carrier board. USB and secondary ethernet ports are working as expected.

I took the files from #93 and created a fresh branch with a stylistically correct commit message in hopes of finishing the work that @c-wilson started.

closes #90 
closes #93

### CODE REVIEW

**Comment by acostach** [comment]
Hi @keenanjohnson and thank you for your contribution!

Please note that the PR will need to adhere to the commit guidelines. One example is available here: https://github.com/balena-os/balena-jetson/pull/60

Also, the jetson devices that are deployed to the dashboard are now maintained in the https://github.com/balena-os/balena-jetson repository, and are updated to newer L4T releases - please see the changelog there. This PR will need to be opened in that repo, with the corresponding dtb for L4T 32.4.2.

As for all community supported boards, the community status needs to be specified in the coffee file, along the false attribute for the private tag, please see: https://github.com/balena-os/balena-jetson/blob/master/photon-nano.coffee#L15 . Also, testing and support (including other users issues) of this device type will have to be undertaken by you.

Thanks again and let us know if you need further guidance for PRing in balena-jetson!

**Comment by keenanjohnson** [comment]
Thanks @acostach !

I'll take a look at that. What's the best way to reach out for support if I get stuck?

**Comment by keenanjohnson** [comment]
Also is L4T 32.4.2 the required release or can I use a previous version?

**Comment by acostach** [comment]
@keenanjohnson in balena-jetson L4T 32.4.2 is currently required. The L4T version is dictated by the current state of meta-tegra layer in that repository. Usually the DTB needs to match, or at least be close to the used version, otherwise the board may have trouble booting. You can ask us here or in the new PR in balena-jetson.

**Comment by keenanjohnson** [comment]
Thanks! Yeah it looks like the provided vendor image doesn't support L4T 32.4.2, so I'll need to contact them and see if I can get one that does.

Thanks!

**Comment by keenanjohnson** [comment]
@acostach when creating a test image from the balena-jetson repo, how do I associate that with my balena account for testing?

**Comment by keenanjohnson** [comment]
Ok I created a pull request here: https://github.com/balena-os/balena-jetson/pull/71

Let's move the discussion there going forward. Thanks for all your help everyone.

**Comment by floion** [comment]
@keenanjohnson since you opened https://github.com/balena-os/balena-jetson/pull/71 can you please close this PR here? Thanks

**Pull request closed without merging**
