### PR TITLE
Add new TX2 Machine with ODMDATA 0x90000

### PR DESCRIPTION
**Pull request by mhodgson**
Also includes the gasket kernel driver to support PCIe-based Coral Edge TPUs.

### CODE REVIEW

**Comment by mhodgson** [comment]
Sorry for the new PR, I FUBARed the other branch trying to fix the commit structure.

**Comment by acostach** [comment]
No worries @mhodgson , this PR is almost perfect! It only needs a couple touches as I see for now:

- jetson-odmdata1-tx2: Add coffee file <- very good, only needs Signed-off-by, just like every commit in the PR.
- jetson-odmdata1-tx2: Add machine to example config <- Should be "samples: Add jetson-odmdata1-tx2 to local.conf" and needs also Signed-off-by.
- gasket: Add gasket module patch <- Needs to be "linux-tegra: Backport gasket driver from linux-coral", again Signed-off-by like for each commit
- gasket: Add Gasket to jetson-odmdata1-tx2 machine <-  to be "linux-tegra: Apply patch and configs for gasket"

As you see, it's pretty much in the form "component: action performed"

Last commit can be dropped and the previous ammended. You can use git rebase --interactive HEAD~<number of commits to go back to for editing>, then use 'e' to mark the commits to be edited in the list, then edit the commit, use 'git add' to add the modified files and then 'git commit --amend' to save the change, followed by git rebase --continue until finished up to the HEAD revision. This way there's no need for a NEW PR as you can git push --force on the current PRed branch. 

Meantime I'll also do a build of this PR on my side and flash it on a board, check if the modules get loaded and odmdata is changed. I assume a build of this branch works fine with you, right?

**Comment by mhodgson** [comment]
@acostach thanks for the git help, I think it's good now. 

I successfully built the image, but haven't had a chance to test it yet. I'm hoping to get to it today but I just started jury duty so I'm away from a device until they release me for the day. I'll keep you posted.

**Comment by mhodgson** [comment]
@acostach a yes, fixed. I have now verified this image on the device and can successfully run inference with the PCI TPU. 

Bad news though: Something isn't quite right with the boot process. The machine eventually gets up and running and works fine, but it is taking between 120-150 seconds to do so. I'm not getting any output on the serial console during this time, so I'm not sure how to debug what the issue might be. Are you seeing the same behavior?

**Comment by mhodgson** [comment]
@acostach I'm wondering if the boot slowness is because of how I added the `gasket.dma_bit_mask=32` module param. It's sitting in a bit of an odd spot. Is there a better/cleaner way to add a new parameter to the kernel cmdline?

**Comment by acostach** [comment]
@mhodgson I've looked into the issue you encounter now and it looks like you are overriding KERNEL_ARGS for this new machine. KERNEL_ARGS used to contain the value "$cbootargs", which provided all the arguments that were set by cboot and passed to u-boot, which in turn passed them to the kernel cmdline when it read the extlinux.conf file. Those arguments are critical for the nvidia drivers that allow the board to boot fine, so we should not override KERNEL_ARGS.

Therefore, can you please check adding the gasket arg this way?
```
KERNEL_ROOTSPEC_append_<myboard> = " gasket.dma_bit_mask=32"
KERNEL_ROOTSPEC_FLASHER_append_<myboard> = " gasket.dma_bit_mask=32"
```

Also, while we're at this, what do you think if gave this board a more suggestive name, something like m2pcie-tx2? Could you please rename it everywhere in these commits, and also have the last 2 changes into a single commit, cause they are working on the same package - see my last comment above. Please note that you need to start a new yocto build with barys when renaming the machine in the coffee file, yocto machine, etc.

**Comment by mhodgson** [comment]
@acostach Done. I will re-build and test.

**Comment by acostach** [comment]
@mhodgson If your intention is to append, then that is fine.

**Comment by mhodgson** [comment]
@acostach I have successfully tested the latest build and no longer see the slowness at boot. I think this is ready to go!

**Comment by acostach** [comment]
@mhodgson thanks for the reply. I can't merge this as it looks like it needs a rebase: "This branch is out-of-date with the base branch".

Can you please do a git fetch in the master branch and then on odmdata-gasket do a rebase master?

Also, it would be great if you could specify the exact url, branch and revision of the gasket driver in that commit's message so that we know what revision it is when we'll update it.

**Comment by mhodgson** [comment]
@acostach better?

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
@balena-ci retest

**Comment by floion** [comment]
https://github.com/balena-os/balena-jetson-skx2/pull/191 was merged guess we can close this PR here?

**Comment by mhodgson** [comment]
Yup! Thanks!

**Pull request closed without merging**
